#!/usr/bin/env python
"""strip outputs from an IPython Notebook
Opens a notebook, strips its output, and writes the outputless version to the original file.
Useful mainly as a git pre-commit hook for users who don't want to track output in VCS.
This does mostly the same thing as the `Clear All Output` command in the notebook UI.
Adapted from rom https://gist.github.com/minrk/6176788 to work with
git filter driver
"""
import sys
import codecs

import nbformat

def strip_output(nb):
    """strip the outputs from a notebook object"""
    if 'worksheets' in nb:
        for ws in nb.worksheets:
            for cell in ws.cells:
                if 'outputs' in cell:
                    cell['outputs'] = []
                if 'prompt_number' in cell:
                    del cell['prompt_number']
    else:
        for cell in nb.cells:
            if 'outputs' in cell:
                cell['outputs'] = []
            if 'execution_count' in cell:
                cell['execution_count'] = None
    return nb

if __name__ == '__main__':
    nb = nbformat.reads(sys.stdin.read(), nbformat.NO_CONVERT)
    nb = strip_output(nb)
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout);
    nbformat.write(nb, sys.stdout, nbformat.NO_CONVERT)

